# Generated by Django 6.0.1 on 2026-01-28 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_view_roles', '0001_initial'),
        ('viewset_usuarios', '0002_user_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api_view_roles.role'),
            preserve_default=False,
        ),
    ]
