# Generated by Django 6.0.1 on 2026-01-30 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('viewset_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id_establecimiento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('id_propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='establecimientos', to='viewset_usuarios.user')),
            ],
        ),
    ]
