# Generated by Django 6.0.1 on 2026-01-30 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('viewset_productos', '0001_initial'),
        ('viewset_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('productos', models.ManyToManyField(related_name='Productos', to='viewset_productos.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='viewset_usuarios.user')),
            ],
        ),
    ]
