name: First contact with GitHub Actions

on:
  push:
    tags:
      - '*'

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build a docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log In to Github container Registery
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build docker image
        run: docker build -t ghcr.io/${{ github.repository }}:${{ github.ref_name }} .

      - name: Push docker image to Github container Registery
        run: docker push ghcr.io/${{ github.repository }}:${{ github.ref_name }}
        
